spring:
 application:
  name: flight-data-ms
 datasource:
   url: jdbc:mysql://localhost:3306/flightdb
   username: root
   password: shilpa 
 jpa:
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect
   show-sql: true  
   hibernate:
    ddl-auto: update
 config:
  server:
   git:
    default-label: master
   import: configserver:http://localhost:8888
server:
 port: 8081
zipkin:
 tracing:
  endpoint: http://localhost:9411