spring:
 application:
  name: payment-ms
 config:
  server:
   git:
    default-label: master
   import: configserver:http://localhost:8888
server:
 port: 8082
zipkin:
 tracing:
  endpoint: http://localhost:9411